// src/app/employee/employee.model.ts
export interface Employee {
    id?: number; // Optional because ID is usually generated by the backend
    first_name: string;
    last_name: string;
    email: string;
    phone?: string;
    address?: string;
    post: string;
    salary?: number;
    status: 'active' | 'inactive';
    admin_id?: number; //  Optional, backend might handle this
    created_at?: string;
    updated_at?: string;
  }